name: Path-Based Trigger Test

on:
  push:

jobs:
  filter-paths:
    name: Filter Changed Paths
    runs-on: ubuntu-latest
    outputs:
      extension: ${{ steps.filter.outputs.extension }}
      auth-ui: ${{ steps.filter.outputs.auth-ui }}
      backend: ${{ steps.filter.outputs.backend }}
      infra: ${{ steps.filter.outputs.infra }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Filter Paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            extension:
              - 'extension/**'
            auth-ui:
              - 'auth-ui/**'
            backend:
              - 'backend/**'
            infra:
              - 'infra/**'

  check-poetry:
    name: check poetry
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: poetry init

  extension-job:
    name: Extension Job
    needs: filter-paths
    if: ${{ needs.filter-paths.outputs.extension == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Extension Changes
        run: echo "Changes detected in the extension directory"

  auth-ui-job:
    name: Auth UI Job
    needs: filter-paths
    if: ${{ needs.filter-paths.outputs.auth-ui == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Auth UI Changes
        run: echo "Changes detected in the auth-ui directory"

  backend-job:
    name: Backend Job
    needs: filter-paths
    if: ${{ needs.filter-paths.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Backend Changes
        run: echo "Changes detected in the backend directory"

  infra-job:
    name: Infra Job
    needs: filter-paths
    if: ${{ needs.filter-paths.outputs.infra == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo Infra Changes
        run: echo "Changes detected in the infra directory"
